apiVersion: v1
kind: Pod
metadata:
  name: kubernetes-pod-test
  labels:
    app: kubernetes-pod-test
spec:
  containers:
    - name: kubernetes-pod-test
      image: arisu1000/simple-container-app:latest
      resources:
        requests:
          cpu: 0.1
          memory: 200M
        limits:
          cpu: 0.5
          memory: 1G
      ports:
        - containerPort: 8080
      env:  
        - name: TEST_ENV
          value: "testenv"
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: CPU_REQUEST
          valueFrom:
            resourceFieldRef:
              containerName: kubernetes-pod-test
              resource: requests.cpu
        - name: CPU_LIMIT
          valueFrom:
            resourceFieldRef:
              containerName: kubernetes-pod-test
              resource: limits.cpu
