apiVersion: v1
kind: Pod
metadata:
  name: kubernetes-pod-test
  labels:
    app: kubernetes-pod-test
spec:
  containers:
    - name: kubernetes-pod-test
      image: arisu1000/simple-container-app:latest
      resources:
        requests:  
          cpu: 0.1
          memory: 200M
        limits:  
          cpu: 0.5
          memory: 1G
      ports:
        - containerPort: 8080
