apiVersion: v1
kind: Pod
metadata:
  name: nodeselector-pod
spec:
  containers:
    - name: nodeselector-pod
      image: arisu1000/simple-container-app:latest
      ports:
        - containerPort: 8080
  nodeSelector:
    disktype: ssd
