apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - name: nginx-nodeselector
    image: nginx
    ports:
    - containerPort: 8080
  nodeSelector:
    disktype: nvm2


apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      nodeSelector:
        disktype: nvm2
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80

