apiVersion: v1
kind: Service
metadata:
  name: my-cip-service
spec:
  type: NodePort
  selector:
    app: metrics
    department: engineering
  ports:
    - protocol: TCP
      port: 80
      targetPort: 50000
      nodePort: 30198


kubectl expose deployment my-deployment-50000 \
 --name my-np-service --type NodePort --protocol TCP --port 80 \
 --target-port 50000