apiVersion: v1
kind: Service
metadata:
  name: my-cip-service
spec:
  type: ClusterIP
  selector:
    app: metrics
    department: sales
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

kubectl expose deployment my-deployment \
 --name my-service --type ClusterIP --protocol TCP \
 --port 80 --target-port 8080

 apiVersion: v1
kind: Service
metadata:
  name: svc-web
spec:
  ClusterIP: 10.96.100.100
  selector:
    app: web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      