apiVersion: v1
kind: Pod
metadata:
  name: podnet-01
spec:
  containers:
  - name: web
    image: nginx
  - name: ubuntu
    image: ubuntu:16.04
    command: ["/bin/sh", "-c", "while : ;do curl http://localhost:80/; sleep 10; done"]


192.168.152.227/32
192.168.152.227/32

kubectl exec podnet-01 -c ubuntu \
 -- curl localhost

192.168.72.189/32
kubectl exec podnet-01 -c ubuntu 'curl' '192.168.152.228'
kubectl exec podnet-01 -- 'curl' '192.168.221.24'




wget https://raw.githubusercontent.com/projectcalico/calico/v3.25.1/manifests/custom-resources.yaml

calicoctl get ippool default-ipv4-ippool -o yaml > calico-
ipool.yaml

apiVersion: v1
kind: Pod
metadata:
  namespace: dns
  name: dns-pod
spec:
  containers:
  - name: dns-pod
    image: arisu1000/simple-container-app:latest
  dnsPolicy: ClusterFirst
  dnsConfig:
    nameservers:
    - 8.8.8.8
    searches:
    - default.svc.cluster.local
    - example.com
    options:
    - name: example01
      value: value01
    - name: example02
