apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx-label
spec:
  selector:
    matchLabels:
      app: nginx-label
  template:
    metadata:
      labels:
        app: nginx-label
    spec:
      containers:
        - name: nginx-container
          image: nginx
          volumeMounts:
            - name: hostpath-volume
              mountPath: /mydata
      volumes:
        - name: hostpath-volume
          hostPath:
            path: /mydata
            type: Directory
