apiVersion: apps/v1
kind: Deployment
metadata:
  name: secretapp
  labels:
    app: secretapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secretapp
  template:
    metadata:
      labels:
        app: secretapp
    spec:
      containers:
        - name: secretapp
          image: arisu1000/simple-container-app:latest
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: volume-secret
              mountPath: "/etc/volume-secret"
              readOnly: true
      volumes:
        - name: volume-secret
          secret:
            secretName: user-pass-secret2
