apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  ports:
    - port: 80
      name: web
  clusterIP: None
  selector:
    app: nginx
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web
spec:
  selector:
    matchLabels:
      app: nginx  # .spec.template.metadata.labels와 일치해야 합니다.
  serviceName: "nginx"
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx  # .spec.selector.matchLabels와 일치해야 합니다.
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
              name: web
